sudo: false
language: generic
matrix:
    include:
        - os: linux

cache:
    directories:
        - /tmp/texlive
        - $HOME/.texlive

before_install: 
- bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk -pdf -interaction=nonstopmode -halt-on-error thesis-sample.tex
after_success:
- mv thesis-sample.pdf ~/
- git checkout --orphan $TRAVIS_BRANCH-pdf
- git rm -rf .
- mv ~/thesis-sample.pdf ./
- git add -f thesis-sample.pdf
- git -c user.name='travis' -c user.email='travis' commit -m "Build thesis"
- git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
